Module5 task1
htmlacademy-adaptive/1061909-cat-energy-21 pull request #14
Opened 2020-12-28 14:29 UTC by Akimba-png

Реализована адаптивная вёрстка главной страницы + проведена оптимизация изображений (растр + svg)

2020-12-29 07:43 UTC, babtshe requested changes
Сгенерированные файлы не должны попадать в репозиторий. 

Вёрстка разъехалась на промежуточных размерах экрана: 
![image](https://user-images.githubusercontent.com/30229773/103267306-58f70980-49c2-11eb-9a45-f68efd4f7cb1.png)
![image](https://user-images.githubusercontent.com/30229773/103267343-62807180-49c2-11eb-9e11-7eadd9d3a47b.png)
![image](https://user-images.githubusercontent.com/30229773/103267390-71ffba80-49c2-11eb-91cc-277951545c77.png)
![image](https://user-images.githubusercontent.com/30229773/103267424-8b086b80-49c2-11eb-8662-2c030fbff033.png)

Шрифты не грузятся: 
![image](https://user-images.githubusercontent.com/30229773/103267490-affcde80-49c2-11eb-8160-b68300ac0550.png)

2020-12-29 07:43 UTC, babtshe commented on source/sass/blocks/features.scss
> +      content: "1";
Чтобы не задавать числа вручную можно использовать `counter`

2020-12-29 09:47 UTC, Akimba-png commented
Поправил пути в шрифтах, добавил счётчик. Сгенерированные изображения планировал удалить после добавления автоматизации.

2020-12-30 13:06 UTC, babtshe approved these changes

2020-12-30 13:07 UTC, merged