Адаптивная графика для главной страницы
htmlacademy-adaptive/1061909-cat-energy-21 pull request #17
Opened 2021-01-17 18:33 UTC by Akimba-png

Добавлен скрипт на слайдер, добавлено лого компании на блок карт.
Со скриптами (особенно карт) наверняка намудрил, но пришло такое решение.
Единственное, размер и положение лого на карте, при изменении вьюпорта, переключается после перезагрузки страницы.

2021-01-18 06:57 UTC, babtshe requested changes

2021-01-18 06:57 UTC, babtshe commented on source/index.html
> +    <div class="page-footer__map" id="map"></div>
Эта область карты - нефункциональна, так как перекрывается: 
![image](https://user-images.githubusercontent.com/30229773/104881983-53626300-5973-11eb-9ccd-5cca740ef930.png)

2021-01-18 06:57 UTC, babtshe commented on source/js/scripts.js
> +      iconImageHref: "../img/map-pin-tablet.png",
с картинкой что-то пошло не так: 
![image](https://user-images.githubusercontent.com/30229773/104882124-8d336980-5973-11eb-9181-f3f0b039823d.png)

2021-01-18 06:57 UTC, babtshe commented on source/sass/blocks/page-footer.scss
> +// }
❗

2021-01-18 15:26 UTC, Akimba-png commented
Поправил область видимости карты, теперь блок с контактами не перекрывает карту.
Поправил пути к иконке на карте. 
Иконка появляется, но опять же смена происходит через обновление страницы. Это допустимо по критериям или лучше вернуть всё на iframe тогда с дефолтной иконкой по центру?

2021-01-18 15:27 UTC, Akimba-png commented
Так же в слайдере поправил положение серого блока с правой стороны. чтобы при изменении размера окна левая граница блока находилась по центру слайдера.
Понимаю, что это не лучшее решение, но не пойму как его по-другому зафиксировать по центру слайдера.

2021-01-19 06:46 UTC, babtshe approved these changes

2021-01-19 06:46 UTC, merged