Разметка главной страницы
htmlacademy-adaptive/1061909-cat-energy-21 pull request #2
Opened 2020-11-17 17:32 UTC by Akimba-png

2020-11-17 17:40 UTC, Akimba-png commented
2.  Вёрстка слайдера.
Сомневаюсь в правильности миксовки блока .slider к основному блоку.
Сейчас получается, что в блоке .slider находятся элементы, которые к нему не относятся, насколько это корректно?
![изображение](https://user-images.githubusercontent.com/70880892/99426449-24008d00-2915-11eb-9a18-6a6b86c335aa.png)

2020-11-18 08:07 UTC, babtshe requested changes
Отдельный блок `wrapper` вполне можно использовать. При этом стоит помнить, что часто не получается сделать его универсальным и в итоге приходится возвращаться к `some-section__wrapper`

`slider` на основном блоке не нужен, так как ничего полезного он там не делает.

2020-11-18 08:07 UTC, babtshe commented on source/index.html
> +          дилеров!
`br` тут лишние, можно будет шириной блока отрегулировать  переносы текста

2020-11-18 08:07 UTC, babtshe commented on source/index.html
> +        <p class="partnership__invite">
названия классов стоит отвязать от содержимого. Что будет, если в будущем надпись поменяется на "не работаем с дилерами", а стиль останется тот же? Название будет вводить в заблуждение.

2020-11-18 08:07 UTC, babtshe commented on source/index.html
> +        </p>
❗`br`

Для адреса есть тег `address`

2020-11-18 11:10 UTC, Akimba-png commented on source/index.html
> +      </a>
Хм, учитывая, что в футере используется логотип без иконки, только текст - решил из разделить. Поправлю. Правильно понимаю, что в футере тогда можно использовать тот же блок .logo?

2020-11-18 11:38 UTC, Akimba-png commented on source/index.html
> +          <li class="features__item">Уже через месяц наслаждайтесь изменениями к лучшему вашего питомца!</li>
Модификаторы добавлю. Не является ли текст превьюшкой статьи? Иными словами не ссылки ли это?

2020-11-18 12:16 UTC, Akimba-png commented on source/index.html
> +        </p>
Поправил. Ранее не использовал address. заглянул на canIUse - по его данным FF не поддерживает тег. Не страшно?
![изображение](https://user-images.githubusercontent.com/70880892/99529471-e8b39c00-29b0-11eb-95a6-6047b75140e9.png)

2020-11-18 13:27 UTC, babtshe commented on source/index.html
> +        </p>
всё хорошо у него с [поддержкой](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address), видимо что-то не то посмотрел.

2020-11-18 13:27 UTC, babtshe commented on source/index.html
> +      </a>
на данном этапе вполне можно

2020-11-18 13:28 UTC, babtshe commented on source/index.html
> +          <li class="features__item">Уже через месяц наслаждайтесь изменениями к лучшему вашего питомца!</li>
нет, просто текст

2020-11-18 13:28 UTC, babtshe approved these changes

2020-11-18 13:29 UTC, merged