Разметка страницы формы
htmlacademy-adaptive/1061909-cat-energy-21 pull request #3
Opened 2020-11-19 18:27 UTC by Akimba-png

2020-11-20 08:12 UTC, babtshe requested changes

2020-11-20 08:12 UTC, babtshe commented on source/form.html
> +    <form class="page-form__form form" action="https://echo.htmlacademy.ru" method="get">
стоит посмотреть [документацию ](https://www.w3schools.com/tags/ref_httpmethods.asp)по методам формы

2020-11-20 08:12 UTC, babtshe commented on source/form.html
> +          <ul class="cat-info__list">
в данном случае список выглядит лишним.

2020-11-20 08:12 UTC, babtshe commented on source/form.html
> +                <input type="text" name="cat name" placeholder="Барсик" required>
имена инпутов можно упростить, убрав префикс `cat `

2020-11-20 08:12 UTC, babtshe commented on source/form.html
> +                <input type="tel" name="tel" placeholder="8 (960) 900-60-90" pattern="[0-9]{1} \([0-9]{3}\) [0-9]{3}-[0-9]{2}-[0-9]{2}" title="[* (***) ***-**-**" required>
заставлять пользователя вводить номер в определённом формате - жестоко. Достаточно будет, если он просто цифры введёт. Всякие красивости вроде скобок и форматирования обычно уже скрипт добавляет.

2020-11-20 08:12 UTC, babtshe commented on source/form.html
> +            <li class="addition__item">
стоит указать одинаковый `name`, но разные `value`. Тогда на сервер данные придут в виде аккуратного массива.

2020-11-20 09:02 UTC, Akimba-png commented on source/form.html
> +    <form class="page-form__form form" action="https://echo.htmlacademy.ru" method="get">
Исправил на post. При вёрстке задавался вопросом какой метод лучше использовать. Остановился на get т.к в форме нет приватной информации (паролей и.т.д.)
Правильно ли я понял, что здесь лучше использовать post из-за наличия поля с текстовым комментарием (т.к. в get есть ограничения на вес и кол-во символов в запросе)?
Ну и телефон, наверное, тоже можно считать приватной информацией.
Или я что-то упускаю ещё?

2020-11-20 11:03 UTC, Akimba-png commented on source/form.html
> +                <input type="tel" name="tel" placeholder="8 (960) 900-60-90" pattern="[0-9]{1} \([0-9]{3}\) [0-9]{3}-[0-9]{2}-[0-9]{2}" title="[* (***) ***-**-**" required>
Согласен, тут перегнул конечно. Но было интересно, как добавить обязательность "()" в паттерне.

2020-11-20 14:41 UTC, babtshe commented on source/form.html
> +    <form class="page-form__form form" action="https://echo.htmlacademy.ru" method="get">
телефон и имя вполне себе приватные данные. `GET` хорошо делать например для поискового запроса, чтобы можно было переслать ссылку на результаты поиска. 
Для формы сбора лидов - однозначно POST.

2020-11-20 14:46 UTC, babtshe requested changes

2020-11-20 14:46 UTC, babtshe commented on source/form.html
> +                <input type="tel" name="tel" placeholder="8 (960) 900-60-90" pattern="[0-9]{11}" title="81234567890" required>
паттерн стоит вообще выпилить на данном этапе. Кто-то любит начинать номер с плюсика, кто-то вставляет дефисы, кто-то пробелы, у кого-то другое количество цифр в номере.

Не нужно задачу разработчика перекладывать на пользователя. Если для записи в базу нужен определённый формат, пусть этим скрипт занимается. 

Чем сложнее заполнить форму, тем меньше будет число собранных заявок.

2020-11-21 13:24 UTC, Akimba-png commented on source/form.html
> +                <input type="tel" name="tel" placeholder="8 (960) 900-60-90" pattern="[0-9]{11}" title="81234567890" required>
Согласен, мудро. А если мы уберём паттерн, это не будет не выполнением критерия:
5.3. При попытке отправить форму, в которой поля для ввода телефона или почты заполнены данными в неподходящем формате, появляется встроенное в браузер сообщение об ошибке.

2020-11-22 13:31 UTC, babtshe commented on source/form.html
> +                <input type="tel" name="tel" placeholder="8 (960) 900-60-90" pattern="[0-9]{11}" title="81234567890" required>
для критерия достаточно `type="tel"`

2020-11-22 13:31 UTC, babtshe approved these changes

2020-11-22 13:32 UTC, merged