Стилизация главной страницы
htmlacademy-adaptive/1061909-cat-energy-21 pull request #6
Opened 2020-11-25 05:57 UTC by Akimba-png

2020-11-25 07:07 UTC, babtshe requested changes

2020-11-25 07:07 UTC, babtshe commented on source/sass/blocks/contacts.scss
> +  @include oswald-normal-black;
со шрифтами такая же история как и с цветами. Шрифт может и поменяться.

2020-11-25 07:07 UTC, babtshe commented on source/sass/blocks/page-header.scss
> +  font-family: "Oswald", "Arial", sans-serif;
шрифт стоит в переменную убрать

2020-11-25 07:07 UTC, babtshe commented on source/sass/global/global.scss
> +}
делать отдельный класс ради такого не нужно, можно реализовать через модификаторы.

2020-11-25 07:07 UTC, babtshe commented on source/sass/global/global.scss
> +}
оптимально будет вынести в переменную только `font-family`, цвета и вес могут меняться, а переопределять может быть не так удобно.

2020-11-25 07:07 UTC, babtshe commented on source/sass/style.scss
> +@import "blocks/visually-hidden.scss";
можно вынести в глобальные стили вместо отдельного блока.

2020-11-25 08:03 UTC, Akimba-png commented on source/sass/blocks/button.scss
> +  background-color: $basic-green;
Согласен. При этом, если привязывать цвета к какой-либо области - не может ли быть в дальнейшем тонкого момента, когда этот цвет будет использован в дизайне не только, допустим, в виде бекграунда какого-либо блока, но и в оформлении текста?

2020-11-25 08:06 UTC, Akimba-png commented on source/sass/blocks/button.scss
> +  background-color: $basic-green;
И если цвет встречается ограниченное кол-во раз на странице, например какой-либо маркер красного цвета, допустимо ли использовать в переменной название цвета в данном случае?

2020-11-25 11:56 UTC, Akimba-png commented on source/sass/global/global.scss
> +}
<span class="uppercase">html</span>&nbsp;Academy</a>
Может в этом случае рациональнее просто заглавными буквами html набрать?
чтобы не плодить у спана элемент и модификатор элемента.
Остановлюсь на этом варианте, если что поправь.

2020-11-26 11:27 UTC, babtshe commented on source/sass/blocks/button.scss
> +  background-color: $basic-green;
прямого запрета нет, это скорее рекомендация.

2020-11-26 11:30 UTC, babtshe commented on source/sass/global/global.scss
> +}
Заглавными не стоит набирать, стилизацию лучше вынести в `css`. Что плохого в использовании модификатора?

2020-11-26 11:33 UTC, babtshe approved these changes

2020-11-26 11:33 UTC, merged