Стилизация страницы формы
htmlacademy-adaptive/1061909-cat-energy-21 pull request #7
Opened 2020-11-27 10:38 UTC by Akimba-png

2020-11-27 15:38 UTC, babtshe requested changes

2020-11-27 15:38 UTC, babtshe commented on source/form.html
> +                <input class="owner-data__input" type="tel" name="tel" placeholder="8 (960) 900-60-90" title="81234567890" required>
лучше использовать нейтральные имена блоков. Такое поле для ввода телефона явно можно использовать не только для ввода данных владельца.

2020-11-27 15:38 UTC, babtshe commented on source/sass/blocks/form.scss
> +  font-family: "Arial", sans-serif;
неплохо бы в переменную положить

2020-11-27 16:24 UTC, Akimba-png commented on source/sass/blocks/form.scss
> +  font-family: "Arial", sans-serif;
Имеется в виду font-family или uppercase тоже стоит замиксовать?

2020-11-27 18:19 UTC, Akimba-png commented on source/sass/blocks/form.scss
> +  font-family: "Arial", sans-serif;
Внёс только font-family в примесь пока. На случай если uppercase изменят

2020-11-30 09:28 UTC, babtshe approved these changes

2020-11-30 09:28 UTC, merged