Адаптивная сетка для главной страницы
htmlacademy-adaptive/1061909-cat-energy-21 pull request #9
Opened 2020-12-05 11:43 UTC by Akimba-png

2020-12-06 10:26 UTC, babtshe requested changes

2020-12-06 10:26 UTC, babtshe commented on source/index.html
> +  </script>
скрипт лучше подключить отдельным файлом по аналогии со стилями. 

Хорошая практика для тех классов, которые используются в скрипте, делать префикс `js-` например `js-navigation-toggle`. В этом случае классы для скриптов и стилизации не пересекаются и при правке вёрстки можно не бояться уронить скрипт.

2020-12-06 10:26 UTC, babtshe commented on source/sass/blocks/instance.scss
> +    @include desctop-padding;
опечатка в названии

2020-12-06 17:47 UTC, Akimba-png commented on source/index.html
> +  </script>
Да, изначально скрипт так и планировал подключать отдельным файлом. Не было понимания, должны ли все JS файлы импортироваться в один по аналогии с style.scss. Сейчас подключил скрипт отдельным файлом.

По префиксу js- Правильно ли понял, что следует создать для каждого используемого в JS класса - новый класс с префиксом (т.е. в данном скрипте добавляем классы .js-main-navigation .js-main-navigation__navigation-toggle .js-main-navigation--no-js? Или достаточно просто добавить префикс в разметку к текущим классам?

2020-12-07 08:44 UTC, Akimba-png commented
По префиксу -JS реализовал такой вариант. Частично добавил новые классы, частично добавил префикс к уже имеющимся классам. Но кажется что-то намудрил.

2020-12-07 13:20 UTC, babtshe commented on source/index.html
> +  </script>
дублировать нет необходимости. Можно сделать имя класса, которое только в скрипте используется. Идея в том, чтобы не вешать стили на классы, которые скриптом используются, и не использовать скрипты на классах только для стилизации. Если нужно и стили и скрипты на одном классе ( например это модификатор, который скрывает элемент), то тут можно без префикса обойтись.

2020-12-07 14:20 UTC, babtshe approved these changes

2020-12-07 14:20 UTC, merged